src/DevRhythm.Web/Controllers/CultureController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace DevRhythm.Web.Controllers
{
    public class CultureController : Controller
    {
        [HttpPost]
        public IActionResult SetCulture(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });
            return LocalRedirect(returnUrl);
        }
    }
}

src/DevRhythm.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DevRhythm</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/reset.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DevRhythm.Web.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100&family=Poppins:wght@100;200;400;600&display=swap" rel="stylesheet">
</head>
<body>
    <header class="position-fixed d-flex align-items-center">
        <nav class="container-fluid p-2 navbar navbar-expand-sm navbar-toggleable-sm container-fluid d-flex align-items-center justify-content-center">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Post" asp-action="Index">DevRhythm</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="search-bar d-flex justify-content-center p-2 m-3 gradient-border-mask">
                    <form method="get" action="/SearchPosts" role="search" class="container-fluid d-flex align-items-center justify-content-between">
                        <input name="keyword" type="search" placeholder="Search" aria-label="Search for content">
                        <button class="search-button" aria-label="Search" type="submit">
                            <i class="fa-solid fa-magnifying-glass fa-lg"></i>
                        </button>
                    </form>
                </div>
                @await Component.InvokeAsync(typeof(DevRhythm.Web.ViewComponents.UserStatusViewComponent))
            </div>
        </nav>
        <div>
            @await Html.PartialAsync("_SetCulturePartial")
        </div>
    </header>
    <div class="toast-container"></div>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/layout.bundle.js"></script>
    <script src="https://kit.fontawesome.com/0e685931d4.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/DevRhythm.Web/Views/Shared/_NotificationPartial.cshtml
@model DevRhythm.App.DTOs.NotificationDto

<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <span>@Model.Sender?.UserName</span>
        <small>@Model.SentAt.ToString("HH:mm:ss")</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body">
        @Model.Message
        <br />
        @if (Model.NotificationType == DevRhythm.Core.Enums.NotificationType.VoteNotification)
        {
            <a asp-action="ShowPost" asp-controller="Post" asp-route-id="@Model.PostDto?.Id"> Post: @Model.PostDto?.Heading</a>
        }
    </div>
</div>

src/DevRhythm.Web/Views/Shared/_NotificationToastPartial.cshtml
@model DevRhythm.App.DTOs.NotificationDto

<div class="toast" role="alert" aria-live="assertive" aria-atomic="true">
    <div class="toast-header">
        <span>@Model.Sender?.UserName</span>
        <small>@Model.SentAt.ToString("HH:mm:ss")</small>
        <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="toast-body">
        @Model.Message
        <br />
        @if (Model.NotificationType == DevRhythm.Core.Enums.NotificationType.VoteNotification)
        {
            <a asp-action="ShowPost" asp-controller="Post" asp-route-id="@Model.PostDto?.Id"> Post: @Model.PostDto?.Heading</a>
        }
    </div>
</div>

src/DevRhythm.Web/Views/Shared/_SetCulturePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IOptions<RequestLocalizationOptions> LocOptions
@inject IViewLocalizer Localizer

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();

    var cultureItems = LocOptions.Value.SupportedUICultures?
        .Select(c => new SelectListItem { Value = c.Name, Text = c.TwoLetterISOLanguageName })
        .ToList();
}

@if (requestCulture is not null)
{
    <form asp-controller="Culture" asp-action="SetCulture" asp-route-returnUrl="@Context.Request.Path" method="post" class="d-flex align-items-center justify-content-center">
        <i class="fa-solid fa-globe dd-icon" aria-label="@Localizer["localization_settings"]"></i>
        <select class="select-main" name="culture" onchange="this.form.submit();"
                          asp-for="@requestCulture.RequestCulture.UICulture.Name"
                          asp-items="cultureItems"></select>
    </form>
}